"use client";
import {useState} from 'react';
import {Bot,CheckCircle2,Eye,EyeOff,KeyRound,LockKeyhole,PlugZap,ShieldCheck,Sparkles} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
export const PROVIDERS=[{id:'openai',name:'OpenAI',tag:'GPT',description:'Responses API'},{id:'anthropic',name:'Claude',tag:'C',description:'Anthropic API'},{id:'gemini',name:'Gemini',tag:'G',description:'Google AI'},{id:'compatible',name:'Custom API',tag:'API',description:'OpenAI-compatible'}];
export type AiStatus={configured:boolean;provider:string;model:string};
export default function AiConnection({config,onChange,onSave,onOpen,busy,errorText}:{config:any;onChange:(c:any)=>void;onSave:(test:boolean)=>Promise<void>;onOpen:()=>void;busy:boolean;errorText:(code:string)=>string}){
 const [visible,setVisible]=useState(false),[message,setMessage]=useState(''),[result,setResult]=useState<'idle'|'saving'|'saved'|'success'|'error'>('idle');
 const provider=PROVIDERS.find(p=>p.id===config.provider)!;
 const edit=(patch:any)=>{onChange({...config,...patch});setMessage('');setResult('idle');};
 async function submit(test:boolean){setResult('saving');setMessage(test?'جارٍ حفظ الإعدادات ثم طلب استجابة من المزود…':'جارٍ حفظ الإعدادات…');try{await onSave(test);setResult(test?'success':'saved');setMessage(test?'نجح الاتصال. استجاب النموذج للمفتاح المحفوظ.':'تم الحفظ. اختبر الاتصال أو انتقل إلى مساعد الذكاء.');}catch(e:any){setResult('error');setMessage(errorText(e.code));}}
 return <div className="connect-studio"><header className="connect-banner"><div className="connect-emblem"><PlugZap size={28}/></div><div><span>QUOTEX V25 / AI CONNECTION</span><h2>ذكاؤك. على منصتك.</h2><p>اختر مزودك واربط مفتاح API من هنا.</p></div><ShieldCheck className="connect-shield" size={35}/></header><form onSubmit={e=>{e.preventDefault();void submit(true);}} className="connect-form">
 <fieldset><legend><b>01</b>اختر مزود الذكاء</legend><RadioGroup value={config.provider} onValueChange={v=>edit({provider:v,model:'',apiKey:'',hasApiKey:false})} className="provider-grid" dir="rtl" disabled={busy}>{PROVIDERS.map(p=><label key={p.id} className={'provider-choice '+(config.provider===p.id?'chosen':'')} htmlFor={'provider-'+p.id}><span className={'provider-monogram '+p.id}>{p.tag}</span><span><strong>{p.name}</strong><small>{p.description}</small></span><RadioGroupItem value={p.id} id={'provider-'+p.id}/></label>)}</RadioGroup></fieldset>
 <fieldset className="credentials-block"><legend><b>02</b>أدخل بيانات الاتصال</legend>{config.provider==='compatible'&&<div><label htmlFor="provider-url">رابط API الأساسي</label><Input id="provider-url" type="url" dir="ltr" value={config.apiUrl} placeholder="https://provider.example/v1" onChange={e=>edit({apiUrl:e.target.value})} required disabled={busy}/><p>اختر هذا الخيار فقط إذا كانت الخدمة تدعم OpenAI-compatible.</p></div>}<div><label htmlFor="provider-model">اسم النموذج في حساب {provider.name}</label><Input id="provider-model" value={config.model} onChange={e=>edit({model:e.target.value})} placeholder="اسم النموذج كما يظهر عند المزود" dir="ltr" required disabled={busy}/><p>انسخ معرّف النموذج الذي يسمح مفتاحك باستخدامه.</p></div><div><label htmlFor="provider-secret"><KeyRound size={15}/> مفتاح {provider.name} API</label><div className="api-secret-field"><Input id="provider-secret" value={config.apiKey} onChange={e=>edit({apiKey:e.target.value})} type={visible?'text':'password'} autoComplete="off" autoCapitalize="none" spellCheck={false} dir="ltr" placeholder={config.hasApiKey?'مفتاح محفوظ ••••':config.provider==='openai'?'sk-…':'ألصق مفتاح API هنا'} disabled={busy}/><button type="button" onClick={()=>setVisible(!visible)} aria-label={visible?'إخفاء المفتاح':'إظهار المفتاح'}>{visible?<EyeOff size={19}/>:<Eye size={19}/>}</button></div><p>{config.hasApiKey?'اترك الحقل فارغًا للاحتفاظ بالمفتاح المحفوظ.':'المطلوب مفتاح API كامل من حساب المزود؛ رابط الدردشة أو كلمة المرور لا يعملان هنا.'}</p></div></fieldset>
 <div className="connect-security"><LockKeyhole size={18}/><p>يُشفّر المفتاح على الخادم. اختباره يرسل طلبًا قصيرًا إلى مزودك وقد يستهلك من رصيد API.</p></div><div className="connect-actions"><Button type="submit" className="primary" disabled={busy||result==='saving'}><PlugZap size={18}/>{result==='saving'?'جارٍ الاتصال…':'حفظ واختبار الاتصال'}</Button><Button type="button" className="secondary" disabled={busy||result==='saving'||!config.model.trim()} onClick={()=>void submit(false)}>حفظ فقط</Button></div>
 {message&&<div className={'connection-feedback '+result} role="status">{result==='success'?<CheckCircle2 size={20}/>:<Bot size={20}/>}<span>{message}</span></div>}{result==='success'&&<Button type="button" className="secondary wide" onClick={onOpen}><Sparkles size={17}/>الانتقال لتحليل الشارت</Button>}
 </form></div>;
}
