const utf8=new TextEncoder();
export class ApiError extends Error { constructor(public status:number, public code:string){super(code);} }
export const hex=(bytes:Uint8Array)=>Array.from(bytes,x=>x.toString(16).padStart(2,'0')).join('');
export const randomHex=(n=32)=>hex(crypto.getRandomValues(new Uint8Array(n)));
export async function keyedHash(secret:string,value:string){if(!secret||secret.length<32)throw new ApiError(503,'server_setup');const k=await crypto.subtle.importKey('raw',utf8.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(new Uint8Array(await crypto.subtle.sign('HMAC',k,utf8.encode(value))));}
export async function sha256(value:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',utf8.encode(value))));}
export function equal(a:string,b:string){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0;}
export function sixDigits(){const max=4294000000;let n;do{n=crypto.getRandomValues(new Uint32Array(1))[0];}while(n>=max);return String(n%1000000).padStart(6,'0');}
async function cipherKey(secret:string){return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',utf8.encode(secret)),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function seal(secret:string,value:unknown){const iv=crypto.getRandomValues(new Uint8Array(12));const data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await cipherKey(secret),utf8.encode(JSON.stringify(value))));return hex(iv)+'.'+hex(data);}
export async function unseal<T>(secret:string,value:string):Promise<T>{const [a,b]=value.split('.'),bytes=(x:string)=>new Uint8Array(x.match(/../g)!.map(h=>parseInt(h,16)));const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(a)},await cipherKey(secret),bytes(b));return JSON.parse(new TextDecoder().decode(raw));}
export function publicHttps(value:string){let u:URL;try{u=new URL(value);}catch{throw new ApiError(400,'invalid_url');}const h=u.hostname.toLowerCase();if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||u.port&&u.port!=='443'||h==='localhost'||!h.includes('.')||h.endsWith('.local')||h.endsWith('.internal')||h.endsWith('.localhost')||h.endsWith('.')||/^\[|^\d|^0x/i.test(h)||h==='metadata.google.internal')throw new ApiError(400,'invalid_url');return u.toString().replace(/\/+$/,'');}
export function originGuard(r:Request){const origin=r.headers.get('origin'),site=new URL(r.url);if(r.headers.get('sec-fetch-site')==='cross-site')throw new ApiError(403,'origin_denied');if(origin&&new URL(origin).host!==site.host&&new URL(origin).host!==r.headers.get('host'))throw new ApiError(403,'origin_denied');if(!r.headers.get('content-type')?.startsWith('application/json'))throw new ApiError(415,'json_required');}
