"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {ChartNoAxesCombined,Minus,Plus,ChevronLeft,ChevronRight,RotateCcw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {assetOf,bands,emaSeries,rsiSeries,cciSeries,macdSeries,type Candle,type Signal} from '@/lib/market';
export type Layers={ema:boolean;bands:boolean;levels:boolean;rsi:boolean;cci:boolean;macd:boolean};
export default function MarketChart({candles,asset,layers,source,signal}:{candles:Candle[];asset:string;layers:Layers;source:string;signal?:Signal}){
 const holder=useRef<HTMLDivElement>(null);const [width,setWidth]=useState(760),[count,setCount]=useState(65),[offset,setOffset]=useState(0),[hover,setHover]=useState<number|null>(null);
 useEffect(()=>{if(!holder.current)return;const observer=new ResizeObserver(entries=>setWidth(Math.max(280,entries[0].contentRect.width)));observer.observe(holder.current);return()=>observer.disconnect();},[]);
 useEffect(()=>{setOffset(0);setHover(null);},[asset,source]);
 useEffect(()=>{if(holder.current)setCount(holder.current.clientWidth<600?36:65);},[]);
 const all=useMemo(()=>{const a=candles.map(x=>x.close);return{e9:emaSeries(a,9),e21:emaSeries(a,21),e50:emaSeries(a,50),bb:bands(candles),rsi:rsiSeries(a),cci:cciSeries(candles),macd:macdSeries(candles)};},[candles]);
 const end=candles.length-Math.min(offset,Math.max(0,candles.length-count)),start=Math.max(0,end-count),c=candles.slice(start,end),w=width,right=76,left=12,top=20,h=360,bottom=28,pw=w-right-left,step=pw/Math.max(1,c.length);
 const bb=all.bb.slice(start,end);const values=c.flatMap(x=>[x.high,x.low]);if(layers.bands)bb.forEach(x=>{if(x)values.push(x.upper,x.lower);});if(layers.ema){for(const key of ['e9','e21','e50'] as const)all[key].slice(start,end).forEach(v=>{if(v!=null)values.push(v);});}
 let min=values.length?Math.min(...values):0,max=values.length?Math.max(...values):1;const padding=(max-min)*.14||max*.0005||.01;min-=padding;max+=padding;
 const x=(i:number)=>left+(i+.5)*step,y=(v:number)=>top+(max-v)/(max-min)*(h-top-bottom),price=(v:number)=>v>=1000?v.toFixed(2):v>=10?v.toFixed(3):v.toFixed(5);
 const path=(arr:(number|null)[],fy=y)=>arr.map((v,i)=>v==null?'':`${i===0||arr[i-1]==null?'M':'L'}${x(i).toFixed(2)},${fy(v).toFixed(2)}`).join(' ');
 const hovered=hover!==null?c[hover]:null,last=c.at(-1),time=(t:number)=>new Date(t*1000).toLocaleTimeString('en-GB',{timeZone:'UTC',hour:'2-digit',minute:'2-digit'});
 function pane(name:string,arr:(number|null)[],lo:number,hi:number,color:string,levels:number[]=[]){const ys=(v:number)=>10+(hi-v)/(hi-lo)*66;return <div className="oscillator"><div className="oscillator-title">{name} <span>{arr.at(-1)?.toFixed(1)??'—'}</span></div><svg viewBox={`0 0 ${w} 85`} role="img" aria-label={`مؤشر ${name}`}><path d={path(arr,ys)} fill="none" stroke={color} strokeWidth="1.4"/>{levels.map(v=><g key={v}><line x1={left} x2={w-right} y1={ys(v)} y2={ys(v)} stroke="#30414f" strokeDasharray="4 4"/><text x={w-right+10} y={ys(v)+4} fontSize="12" fill="#99afbc">{v}</text></g>)}</svg></div>;}
 return <div ref={holder} className="pro-chart">
 {!c.length?<div className="empty-chart"><span className="chart-empty-icon"><ChartNoAxesCombined/></span><span className="chart-empty-kicker">VAP PRO · CANDLESTICK TERMINAL</span><b>جاهز لقراءة السوق.</b><p>فعّل سيرفر الأسعار من الإدارة لعرض شموع دقيقة. يمكنك اختيار محاكاة DEMO لاستكشاف الشارت.</p></div>:<>
 <div className="chart-status"><div className="price-value" dir="ltr">{price((hovered||last!).close)}<small>{source==='demo'?'DEMO':'OTC'}</small></div><div className="chart-meta">{['open','high','low','close'].map((k,i)=><span key={k}>{['O','H','L','C'][i]} <b>{price((hovered||last!)[k as 'open'])}</b></span>)}</div></div>
 <svg className="chart-canvas" viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`شارت شموع ${assetOf(asset).label}، ${source==='demo'?'أسعار محاكاة':'أسعار المصدر المتصل'}`} onPointerMove={ev=>{const r=ev.currentTarget.getBoundingClientRect();const at=(ev.clientX-r.left)*w/r.width;setHover(Math.max(0,Math.min(c.length-1,Math.floor((at-left)/step))));}} onPointerLeave={()=>setHover(null)}>
 {[0,1,2,3,4].map(i=>{const v=min+(max-min)*i/4;return <g key={i}><line x1={left} x2={w-right} y1={y(v)} y2={y(v)} stroke="#233643"/><text x={w-right+9} y={y(v)+4} fill="#9bb0bf" fontFamily="Arial" fontSize="12">{price(v)}</text></g>;})}
 {c.map((v,i)=>i%Math.max(1,Math.round(c.length/(width>500?5:3)))===0?<g key={v.time}><line x1={x(i)} x2={x(i)} y1={top} y2={h-bottom} stroke="#1d2f3c"/><text x={x(i)} y={h-8} textAnchor="middle" fontFamily="Arial" fontSize="12" fill="#9bb0bf">{time(v.time)}</text></g>:null)}
 {layers.bands&&<><path d={path(bb.map(v=>v?.upper??null))} stroke="#6c9fbc" strokeWidth="1" fill="none" strokeDasharray="4 3"/><path d={path(bb.map(v=>v?.lower??null))} stroke="#6c9fbc" strokeWidth="1" fill="none" strokeDasharray="4 3"/></>}
 {layers.levels&&c.length>=24&&[Math.min(...c.slice(-24).map(v=>v.low)),Math.max(...c.slice(-24).map(v=>v.high))].map((v,i)=><line key={i} x1={left} x2={w-right} y1={y(v)} y2={y(v)} stroke={i?'#f5b554':'#37d9c0'} strokeDasharray="6 5"/>)}
 {c.map((v,i)=>{const up=v.close>=v.open,color=up?'#30e3a7':'#ff6687';return <g key={v.time}><line x1={x(i)} x2={x(i)} y1={y(v.high)} y2={y(v.low)} stroke={color} strokeWidth="1"/><rect x={x(i)-step*.3} y={Math.min(y(v.open),y(v.close))} width={Math.max(1,step*.6)} height={Math.max(1,Math.abs(y(v.open)-y(v.close)))} rx=".8" fill={color}/></g>;})}
 {layers.ema&&(['e9','e21','e50'] as const).map((k,i)=><path key={k} d={path(all[k].slice(start,end))} fill="none" stroke={['#3de5c4','#ffcf78','#a89bff'][i]} strokeWidth="1.35"/>)}
 {last&&<g><line x1={left} x2={w-right} y1={y(last.close)} y2={y(last.close)} stroke="#3ceab1" strokeDasharray="3 3"/><rect x={w-right} y={y(last.close)-10} width={right-1} height="21" rx="3" fill="#037c61"/><text x={w-right+6} y={y(last.close)+4} fill="white" fontFamily="Arial" fontSize="12">{price(last.close)}</text></g>}
 {signal?.asset===asset&&signal.entry_price&&Number(signal.entry_price)>=min&&Number(signal.entry_price)<=max&&<g><line x1={left} x2={w-right} y1={y(Number(signal.entry_price))} y2={y(Number(signal.entry_price))} stroke="#f3c263" strokeDasharray="8 3"/><text x={left+4} y={y(Number(signal.entry_price))-5} fontSize="12" fill="#f3c263">ENTRY {signal.direction}</text></g>}
 {hover!==null&&hovered&&<g><line x1={x(hover)} x2={x(hover)} y1={top} y2={h-bottom} stroke="#b6e2f1" strokeDasharray="3 4"/><circle cx={x(hover)} cy={y(hovered.close)} r="3" fill="#b6e2f1"/><rect x={Math.max(5,Math.min(w-130,x(hover)-55))} y={top} width="110" height="22" rx="4" fill="#23526a"/><text x={Math.max(5,Math.min(w-130,x(hover)-55))+55} y={top+15} textAnchor="middle" fill="white" fontFamily="Arial" fontSize="12">{time(hovered.time)} UTC</text></g>}
 </svg>
 <div className="chart-legend">{layers.ema&&<><span style={{color:'#3de5c4'}}><i/>EMA 9</span><span style={{color:'#ffcf78'}}><i/>EMA 21</span><span style={{color:'#a89bff'}}><i/>EMA 50</span></>}{layers.bands&&<span><i/>BOLLINGER 20, 2</span>}{layers.levels&&<span><i/>SUPPORT / RESISTANCE</span>}<div className="row-actions" style={{marginLeft:'auto'}}><Button variant="ghost" className="small-button" aria-label="شموع أقدم" onClick={()=>setOffset(Math.min(candles.length-count,offset+20))} disabled={candles.length-count<=offset}><ChevronLeft size={14}/></Button><Button variant="ghost" className="small-button" aria-label="تصغير الشارت" onClick={()=>setCount(Math.min(140,count+15))}><Minus size={14}/></Button><Button variant="ghost" className="small-button" aria-label="تكبير الشارت" onClick={()=>setCount(Math.max(20,count-15))}><Plus size={14}/></Button><Button variant="ghost" className="small-button" aria-label="شموع أحدث" onClick={()=>setOffset(Math.max(0,offset-20))} disabled={!offset}><ChevronRight size={14}/></Button><Button variant="ghost" className="small-button" aria-label="آخر الشموع" onClick={()=>{setOffset(0);setCount(width<600?36:65);}}><RotateCcw size={13}/></Button></div></div>
 {layers.rsi&&pane('RSI 14',all.rsi.slice(start,end),0,100,'#b8a7ff',[30,70])}
 {layers.cci&&pane('CCI 20',all.cci.slice(start,end),Math.min(-200,...all.cci.slice(start,end).map(v=>v??0)),Math.max(200,...all.cci.slice(start,end).map(v=>v??0)),'#ffcd78',[-100,100])}
 {layers.macd&&(()=>{const v=all.macd.slice(start,end).map(v=>v.hist),m=Math.max(...v.map(v=>Math.abs(v??0)),.0000001);return pane('MACD HISTOGRAM 12, 26, 9',v,-m,m,'#3de5c4',[0]);})()}
 </>}
 </div>;
}
